superhumans:
    captainamerica:
        display-name: "&4C&9apt&fain_&4A&9mer&4ica"
        equip-phrase: "&4Those who deny freedom to others deserve it not for themselves."
        potion-effects:
            - STRENGTH:5
            - HEALTH_BOOST:4
        items:
            shield:
                material: SHIELD
                amount: 1
                display-name: "&4C&9apt&fain_&4A&9mer&4ica's &9Shield"
                enchantments:
                   - DURABILITY:3
                   - MENDING:1
                shield-meta:
                   base-color: ORANGE
                   patterns:
                    - HALF_HORIZONTAL_MIRROR:RED
                    - HALF_HORIZONTAL_MIRROR:RED
                    - CROSS:BLUE
                    - STRIPE_CENTER:BLUE
                    - STRIPE_MIDDLE:BLUE
                    - FLOWER:WHITE