superhumans:
    captainamerica:
       display-name: '&4C'
          potion-effects:
             - STRENGTH:5
             - HEALTH_BOOST:4
          items:
            shield: 'gsonStuff'
               amount: 1
               display-name: '&4C&9apt&fain_&4A&9mer&4ica\'s &9Shield'
               enchantments:
                  - DURABILITY:3
                  - MENDING:1
                  - 'leather-armor-color: r:g:b'
               shield-meta:
                 base-color: ORANGE
                 patterns:
                    - HALF_HORIZONTAL_MIRROR:RED
                    - HALF_HORIZONTAL_MIRROR:RED
                    - CROSS:BLUE
                    - STRIPE_CENTER:BLUE
                    - STRIPE_MIDDLE:BLUE
                    - FLOWER:WHITE